server:
  port: 10003

spring:
  application:
    name: outsourcing_system_hangzhou

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hangzhou_customer?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect